#!/usr/bin/env bash
set -euo pipefail

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SHARED_ENV_DEFAULT="/root/dev/env/future-coach-app.shared.env"
CADDYFILE="/etc/caddy/Caddyfile"
PREVIEWS_DIR="/etc/futurecoach/previews.d"
TUNNEL_CONFIG="/root/.cloudflared/config.yml"
TUNNEL_NAME="dev-previews-futurecoach"
DEFAULT_DOMAIN="futurecoach.dev"
DEFAULT_APP_PORT_START=8081
DEFAULT_API_PORT_START=8787
MAX_PORT_SCAN=25

usage() {
  cat <<'EOF'
Usage:
  develop.sh preview up <name> [--app-port <port> --api-port <port> | --auto-ports] --worktree <path> [--domain <domain>] [--shared-env <path>] [--launch]
  develop.sh preview check <name> [--domain <domain>]
  develop.sh preview down <name> [--worktree <path>] [--stop]
  develop.sh preview suggest-ports

Examples:
  develop.sh preview up sam-test --app-port 8081 --api-port 8787 --worktree /root/dev/worktrees/future-coach-app/sam-test
  develop.sh preview up marisa-test --auto-ports --worktree /root/dev/worktrees/future-coach-app/marisa-test --launch
  develop.sh preview check sam-test
  develop.sh preview down sam-test --worktree /root/dev/worktrees/future-coach-app/sam-test --stop
  develop.sh preview suggest-ports
EOF
}

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || fail "Missing required command: $1"
}

resolve_bun() {
  if command -v bun >/dev/null 2>&1; then
    command -v bun
    return 0
  fi
  local candidate
  for candidate in /root/.bun/bin/bun /usr/local/bin/bun /usr/bin/bun; do
    if [[ -x "$candidate" ]]; then
      echo "$candidate"
      return 0
    fi
  done
  return 1
}

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    fail "This command needs root privileges because it writes Caddy config and reloads services."
  fi
}

port_in_use() {
  local port="$1"
  ss -ltn "( sport = :$port )" | tail -n +2 | grep -q .
}

ensure_file() {
  local path="$1"
  [[ -f "$path" ]] || fail "Required file not found: $path"
}

ensure_dir() {
  local path="$1"
  [[ -d "$path" ]] || fail "Required directory not found: $path"
}

preview_config_contains_port() {
  local port="$1"
  grep -Rqs "127.0.0.1:$port" "$PREVIEWS_DIR"/*.caddy 2>/dev/null
}

find_next_port_pair() {
  local i app_port api_port
  for ((i=0; i<MAX_PORT_SCAN; i++)); do
    app_port=$((DEFAULT_APP_PORT_START + i))
    api_port=$((DEFAULT_API_PORT_START + i))
    if ! preview_config_contains_port "$app_port" && ! preview_config_contains_port "$api_port" && ! port_in_use "$app_port" && ! port_in_use "$api_port"; then
      echo "$app_port $api_port"
      return 0
    fi
  done
  return 1
}

start_tunnel_if_needed() {
  if ! pgrep -af "cloudflared tunnel --config $TUNNEL_CONFIG run $TUNNEL_NAME" >/dev/null; then
    nohup cloudflared tunnel --config "$TUNNEL_CONFIG" run "$TUNNEL_NAME" >/tmp/cloudflared-futurecoach.log 2>&1 &
    sleep 3
  fi
}

reload_caddy() {
  caddy validate --config "$CADDYFILE" >/dev/null
  caddy reload --config "$CADDYFILE" >/dev/null
}

validate_name() {
  [[ "$1" =~ ^[a-z0-9-]+$ ]] || fail "Preview name must contain only lowercase letters, numbers, and hyphens"
}

validate_port() {
  [[ "$1" =~ ^[0-9]+$ ]] || fail "Invalid port: $1"
}

write_env_file() {
  local target="$1"
  cat > "$target" <<EOF
# Generated by $SKILL_DIR/scripts/develop.sh for $PREVIEW_NAME
DATABASE_URL="$DATABASE_URL"
BETTER_AUTH_SECRET="$BETTER_AUTH_SECRET"
BETTER_AUTH_URL="$PREVIEW_ORIGIN"
API_URL="$PREVIEW_ORIGIN"
PORT=$API_PORT
EXPO_PUBLIC_API_URL="$PREVIEW_ORIGIN"
TWILIO_ACCOUNT_SID="$TWILIO_ACCOUNT_SID"
TWILIO_AUTH_TOKEN="$TWILIO_AUTH_TOKEN"
TWILIO_VERIFY_SERVICE_SID="$TWILIO_VERIFY_SERVICE_SID"
WEB_APP_URL="$PREVIEW_ORIGIN"
EOF
}

write_preview_config() {
  local preview_match api_match
  preview_match="preview_${PREVIEW_NAME//-/_}"
  api_match="${preview_match}_api"
  cat > "$PREVIEW_FILE" <<EOF
@$preview_match host $PREVIEW_HOST
handle @$preview_match {
    @$api_match path /api/*
    handle @$api_match {
        reverse_proxy 127.0.0.1:$API_PORT
    }

    reverse_proxy 127.0.0.1:$APP_PORT
}
EOF
}

process_log_dir() {
  echo "/tmp/futurecoach-preview"
}

api_log_file() {
  echo "$(process_log_dir)/${PREVIEW_NAME}-api.log"
}

app_log_file() {
  echo "$(process_log_dir)/${PREVIEW_NAME}-app.log"
}

api_pid_file() {
  echo "$(process_log_dir)/${PREVIEW_NAME}-api.pid"
}

app_pid_file() {
  echo "$(process_log_dir)/${PREVIEW_NAME}-app.pid"
}

ensure_dependencies() {
  local bun_dir run_path
  bun_dir="$(dirname "$BUN_BIN")"
  run_path="$bun_dir:$PATH"

  if [[ -d "$WORKTREE/node_modules" ]]; then
    return 0
  fi

  echo "Installing dependencies in $WORKTREE" >&2
  (
    cd "$WORKTREE"
    env PATH="$run_path" "$BUN_BIN" install
  )
}

start_processes() {
  local log_dir api_log app_log api_pid app_pid
  log_dir="$(process_log_dir)"
  api_log="$(api_log_file)"
  app_log="$(app_log_file)"
  api_pid="$(api_pid_file)"
  app_pid="$(app_pid_file)"

  mkdir -p "$log_dir"

  cd "$WORKTREE"
  local bun_dir run_path
  bun_dir="$(dirname "$BUN_BIN")"
  run_path="$bun_dir:$PATH"
  ensure_dependencies
  nohup env PATH="$run_path" PORT="$API_PORT" "$BUN_BIN" --filter=api dev >"$api_log" 2>&1 &
  echo $! > "$api_pid"
  nohup env PATH="$run_path" "$BUN_BIN" --filter=app web --port "$APP_PORT" >"$app_log" 2>&1 &
  echo $! > "$app_pid"

  sleep 8

  if ! port_in_use "$API_PORT"; then
    tail -n 80 "$api_log" >&2 || true
    fail "API failed to start on port $API_PORT"
  fi

  if ! port_in_use "$APP_PORT"; then
    tail -n 120 "$app_log" >&2 || true
    fail "App failed to start on port $APP_PORT"
  fi
}

stop_processes() {
  local pid_file pid
  for pid_file in "$(api_pid_file)" "$(app_pid_file)"; do
    if [[ -f "$pid_file" ]]; then
      pid="$(cat "$pid_file")"
      kill "$pid" 2>/dev/null || true
      rm -f "$pid_file"
    fi
  done
}

smoke_check() {
  local root_status auth_status options_status body
  root_status="$(curl -s -o /tmp/preview-root.out -w '%{http_code}' "https://$PREVIEW_HOST/")"
  auth_status="$(curl -s -o /tmp/preview-auth.out -w '%{http_code}' "https://$PREVIEW_HOST/api/auth/get-session")"
  options_status="$(curl -s -o /tmp/preview-options.out -w '%{http_code}' -X OPTIONS "https://$PREVIEW_HOST/api/auth/sign-in/phone-number" \
    -H "Origin: https://$PREVIEW_HOST" \
    -H 'Access-Control-Request-Method: POST' \
    -H 'Access-Control-Request-Headers: content-type')"

  [[ "$root_status" == "200" ]] || fail "Preview root check failed with status $root_status"
  [[ "$auth_status" == "200" ]] || fail "Auth session check failed with status $auth_status"
  [[ "$options_status" == "204" ]] || fail "Auth preflight check failed with status $options_status"

  body="$(curl -s "https://$PREVIEW_HOST/")"
  if grep -q 'http://localhost:' <<<"$body"; then
    fail "Preview HTML still references localhost"
  fi
}

TOP_LEVEL_COMMAND="${1:-}"
[[ -n "$TOP_LEVEL_COMMAND" ]] || { usage; exit 1; }
shift || true

case "$TOP_LEVEL_COMMAND" in
  preview)
    SUBCOMMAND="${1:-}"
    [[ -n "$SUBCOMMAND" ]] || fail "Missing preview subcommand"
    shift || true

    case "$SUBCOMMAND" in
      up)
        PREVIEW_NAME="${1:-}"
        [[ -n "$PREVIEW_NAME" ]] || fail "Missing preview name"
        shift || true
        validate_name "$PREVIEW_NAME"

        APP_PORT=""
        API_PORT=""
        AUTO_PORTS=0
        LAUNCH=0
        DOMAIN="$DEFAULT_DOMAIN"
        SHARED_ENV="$SHARED_ENV_DEFAULT"
        WORKTREE=""

        while [[ $# -gt 0 ]]; do
          case "$1" in
            --app-port)
              APP_PORT="$2"
              shift 2
              ;;
            --api-port)
              API_PORT="$2"
              shift 2
              ;;
            --auto-ports)
              AUTO_PORTS=1
              shift
              ;;
            --launch)
              LAUNCH=1
              shift
              ;;
            --domain)
              DOMAIN="$2"
              shift 2
              ;;
            --shared-env)
              SHARED_ENV="$2"
              shift 2
              ;;
            --worktree)
              WORKTREE="$2"
              shift 2
              ;;
            *)
              fail "Unknown option: $1"
              ;;
          esac
        done

        [[ -n "$WORKTREE" ]] || fail "Missing --worktree"
        ensure_dir "$WORKTREE"

        if [[ "$AUTO_PORTS" -eq 1 ]]; then
          if [[ -n "$APP_PORT" || -n "$API_PORT" ]]; then
            fail "Use either explicit ports or --auto-ports, not both"
          fi
          read -r APP_PORT API_PORT < <(find_next_port_pair) || fail "Could not find a free preview port pair"
        else
          [[ -n "$APP_PORT" ]] || fail "Missing --app-port"
          [[ -n "$API_PORT" ]] || fail "Missing --api-port"
        fi

        validate_port "$APP_PORT"
        validate_port "$API_PORT"

        require_root
        require_cmd curl
        require_cmd caddy
        require_cmd cloudflared
        require_cmd ss
        ensure_file "$SHARED_ENV"
        ensure_file "$TUNNEL_CONFIG"
        ensure_dir "$PREVIEWS_DIR"
        ensure_dir "$WORKTREE/apps/api"
        ensure_dir "$WORKTREE/apps/app"

        if [[ "$APP_PORT" == "$API_PORT" ]]; then
          fail "App port and API port must be different"
        fi

        PREVIEW_HOST="$PREVIEW_NAME.$DOMAIN"
        PREVIEW_ORIGIN="https://$PREVIEW_HOST"
        PREVIEW_FILE="$PREVIEWS_DIR/$PREVIEW_NAME.caddy"

        if [[ -f "$PREVIEW_FILE" ]]; then
          echo "Updating existing preview mapping for $PREVIEW_HOST" >&2
        fi

        BUN_BIN="$(resolve_bun)" || fail "Missing required command: bun"

        # shellcheck disable=SC1090
        set -a
        source "$SHARED_ENV"
        set +a

        : "${DATABASE_URL:?DATABASE_URL missing from shared env}"
        : "${BETTER_AUTH_SECRET:?BETTER_AUTH_SECRET missing from shared env}"
        TWILIO_ACCOUNT_SID="${TWILIO_ACCOUNT_SID:-}"
        TWILIO_AUTH_TOKEN="${TWILIO_AUTH_TOKEN:-}"
        TWILIO_VERIFY_SERVICE_SID="${TWILIO_VERIFY_SERVICE_SID:-}"

        write_env_file "$WORKTREE/.env"
        write_env_file "$WORKTREE/apps/api/.env"
        write_env_file "$WORKTREE/apps/app/.env"

        if [[ "$LAUNCH" -eq 1 ]]; then
          stop_processes
          start_processes
        else
          if ! port_in_use "$APP_PORT"; then
            fail "App port $APP_PORT is not listening. Start the web app before publishing the preview, or use --launch."
          fi

          if ! port_in_use "$API_PORT"; then
            fail "API port $API_PORT is not listening. Start the API before publishing the preview, or use --launch."
          fi
        fi

        write_preview_config
        reload_caddy
        start_tunnel_if_needed
        smoke_check

        echo "Preview ready: $PREVIEW_ORIGIN"
        echo "Worktree: $WORKTREE"
        echo "App port: $APP_PORT"
        echo "API port: $API_PORT"
        if [[ "$LAUNCH" -eq 1 ]]; then
          echo "Launch mode: yes"
        fi
        ;;

      check)
        PREVIEW_NAME="${1:-}"
        [[ -n "$PREVIEW_NAME" ]] || fail "Missing preview name"
        shift || true
        validate_name "$PREVIEW_NAME"
        DOMAIN="$DEFAULT_DOMAIN"
        while [[ $# -gt 0 ]]; do
          case "$1" in
            --domain)
              DOMAIN="$2"
              shift 2
              ;;
            *)
              fail "Unknown option: $1"
              ;;
          esac
        done
        require_cmd curl
        PREVIEW_HOST="$PREVIEW_NAME.$DOMAIN"
        smoke_check
        echo "Preview healthy: https://$PREVIEW_HOST"
        ;;

      down)
        PREVIEW_NAME="${1:-}"
        [[ -n "$PREVIEW_NAME" ]] || fail "Missing preview name"
        shift || true
        validate_name "$PREVIEW_NAME"
        DOMAIN="$DEFAULT_DOMAIN"
        WORKTREE=""
        STOP=0
        while [[ $# -gt 0 ]]; do
          case "$1" in
            --worktree)
              WORKTREE="$2"
              shift 2
              ;;
            --stop)
              STOP=1
              shift
              ;;
            --domain)
              DOMAIN="$2"
              shift 2
              ;;
            *)
              fail "Unknown option: $1"
              ;;
          esac
        done
        require_root
        PREVIEW_FILE="$PREVIEWS_DIR/$PREVIEW_NAME.caddy"
        rm -f "$PREVIEW_FILE"
        reload_caddy
        if [[ "$STOP" -eq 1 ]]; then
          stop_processes
        fi
        echo "Preview removed: $PREVIEW_NAME"
        ;;

      suggest-ports)
        read -r APP_PORT API_PORT < <(find_next_port_pair) || fail "Could not find a free preview port pair"
        echo "Suggested app port: $APP_PORT"
        echo "Suggested API port: $API_PORT"
        ;;

      *)
        usage
        exit 1
        ;;
    esac
    ;;

  *)
    usage
    exit 1
    ;;
esac
